#!/usr/bin/env bash
#
# Set up (or repair) the lab: create the nested source worktree at tree/ and
# install the source tree's ignore rules into it.
#
#     tools/bootstrap.sh [branch]        # default: integration
#
# IDEMPOTENT and cheap — re-run it any time. It is the fix for:
#   * a fresh clone (tree/ does not exist yet)
#   * `git clean -xdf` inside tree/ (deletes the generated tree/.gitignore)
#   * the lab having been moved or renamed (core.excludesFile holds an absolute
#     path, so it must be rewritten)
#
# Why any of this is needed: git NEVER applies ignore rules across a repository
# boundary, so the lab's own .gitignore cannot reach into tree/ — tree/ is a
# separate worktree and its own root. The source tree deliberately commits no
# .gitignore of its own (that is the point: `git diff upstream feature/X` is the
# mailable patch, with no infra in it), so the rules have to be installed from
# out here. See docs/reorg-plan.md.
set -euo pipefail

LAB="$(cd "$(dirname "$0")/.." && pwd)"
BRANCH="${1:-integration}"
TREE="$LAB/tree"
SRC="$LAB/gitignore-src"

[ -f "$SRC" ] || { echo "error: $SRC missing — is this the lab?" >&2; exit 1; }

# --- 1. the nested source worktree ----------------------------------------
if [ -d "$TREE/.git" ] || [ -f "$TREE/.git" ]; then
	echo "tree/ exists: $(git -C "$TREE" rev-parse --abbrev-ref HEAD) ($(git -C "$TREE" rev-parse --short HEAD))"
else
	echo "creating tree/ on '$BRANCH' ..."
	git -C "$LAB" worktree add "$TREE" "$BRANCH"
fi

# --- 2. ignore rules, two ways --------------------------------------------
# (a) A GENERATED, untracked .gitignore that lists ITSELF. Git reads ignore
#     files from the working tree rather than the index, so this is fully
#     effective while staying invisible to `git status` — and `git add -A`
#     cannot stage it. This is the copy ordinary tools (VS Code, ripgrep, fd)
#     see, which core.excludesFile alone would not give us.
{
	echo "# GENERATED by the lab's tools/bootstrap.sh — do not commit, do not edit."
	echo "# Edit ../gitignore-src instead, then re-run tools/bootstrap.sh."
	echo "# This file ignores itself, so it can never be committed by accident."
	echo ".gitignore"
	echo
	cat "$SRC"
} > "$TREE/.gitignore"

# (b) A backstop: `git clean -xdf` deletes the file above (it is ignored), which
#     would leave the tree with no rules at all — and `git add -A` would then
#     happily commit build junk onto a branch bound for upstream. This survives
#     that. Absolute path, so it must be rewritten if the lab ever moves.
git -C "$TREE" config core.excludesFile "$SRC"

# --- 3. the built emulator, where the installs expect it -------------------
# qmake writes the binary to the source-tree root; the installs' `run` scripts
# look for it at the lab root (their ../../). Symlink rather than copy so it
# never goes stale.
for b in rpcemu-interpreter rpcemu-recompiler; do
	ln -sfn "tree/$b" "$LAB/$b"
done

echo
echo "lab      : $LAB"
echo "tree     : $TREE  ($(git -C "$TREE" rev-parse --abbrev-ref HEAD))"
echo "ignores  : tree/.gitignore (generated, self-ignoring) + core.excludesFile -> gitignore-src"
echo
echo "Verify with:  git -C tree status --porcelain      # should be empty"
echo "Switch tree:  git -C tree checkout <branch>       # ignores follow automatically"
